#!/bin/bash

# Copyright (C) 2016  Stefan Vargyas
# 
# This file is part of German-Num.
# 
# German-Num is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# German-Num is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with German-Num.  If not, see <http://www.gnu.org/licenses/>.

#
# File generated by a command like:
# $ gen-test -T eins
#

[[ "$1" =~ ^-u[0-9]+$ ]] &&
u="${1:2}" ||
u=""

diff -u$u -L eins.old <(echo \
'$ test -x ./calc
$ spaces() { ssed -R '\''s/Billi(?:arde(?:n)?|on(?:en)?)|Milli(?:arde(?:n)?|on(?:en)?)|acht|drei|e(?:in(?:e|s)?|lf)|fuenf|hundert|n(?:eun|ull)|s(?:ech(?:s)?|ieb(?:en)?|sig)|tausend|und|vier|z(?:ehn|ig|w(?:an|ei|oelf))/ \0 /g;s/ {2,}/ /g;s/^ //;s/ $//'\'' ${1:+"$1"}; }
$ eins() { if [ "$1" == '\''-s'\'' ]; then shift; eins "$@"|spaces; else ssed -R '\''s/elf/'\''"$2"'\''/g;s/ein[es]?/'\''"$1"'\''/g;s/(?<=Million)(?!en)/en/g'\'' ein2.txt; fi; }
$ calc() { ./calc -i "$@"; }
$ calc -N < ein.txt
1
11
111
1111
11111
111111
1111111
11111111
111111111
1111111111
11111111111
111111111111
$ calc -E < ein.txt
1.000000
11.000000
111.000000
1111.000000
11111.000000
111111.000000
1111111.000000
11111111.000000
111111111.000000
1111111111.000000
11111111111.000000
111111111111.000000
$ spaces ein.txt|calc -N -s
1
11
111
1111
11111
111111
1111111
11111111
111111111
1111111111
11111111111
111111111111
$ spaces ein.txt|calc -E -s
1.000000
11.000000
111.000000
1111.000000
11111.000000
111111.000000
1111111.000000
11111111.000000
111111111.000000
1111111111.000000
11111111111.000000
111111111111.000000
$ calc -N < ein2.txt
1
11
111
1111
11111
111111
1111111
11111111
111111111
1111111111
11111111111
111111111111
$ calc -E < ein2.txt
1.000000
11.000000
111.000000
1111.000000
11111.000000
111111.000000
1111111.000000
11111111.000000
111111111.000000
1111111111.000000
11111111111.000000
111111111111.000000
$ spaces ein2.txt|calc -N -s
1
11
111
1111
11111
111111
1111111
11111111
111111111
1111111111
11111111111
111111111111
$ spaces ein2.txt|calc -E -s
1.000000
11.000000
111.000000
1111.000000
11111.000000
111111.000000
1111111.000000
11111111.000000
111111111.000000
1111111111.000000
11111111111.000000
111111111111.000000
$ eins zwei zweiundzwanzig|calc -N
2
22
222
2222
22222
222222
2222222
22222222
222222222
2222222222
22222222222
222222222222
$ eins zwei zweiundzwanzig|calc -E
2.000000
22.000000
222.000000
2222.000000
22222.000000
222222.000000
2222222.000000
22222222.000000
222222222.000000
2222222222.000000
22222222222.000000
222222222222.000000
$ eins -s zwei zweiundzwanzig|calc -N -s
2
22
222
2222
22222
222222
2222222
22222222
222222222
2222222222
22222222222
222222222222
$ eins -s zwei zweiundzwanzig|calc -E -s
2.000000
22.000000
222.000000
2222.000000
22222.000000
222222.000000
2222222.000000
22222222.000000
222222222.000000
2222222222.000000
22222222222.000000
222222222222.000000
$ eins drei dreiunddreissig|calc -N
3
33
333
3333
33333
333333
3333333
33333333
333333333
3333333333
33333333333
333333333333
$ eins drei dreiunddreissig|calc -E
3.000000
33.000000
333.000000
3333.000000
33333.000000
333333.000000
3333333.000000
33333333.000000
333333333.000000
3333333333.000000
33333333333.000000
333333333333.000000
$ eins -s drei dreiunddreissig|calc -N -s
3
33
333
3333
33333
333333
3333333
33333333
333333333
3333333333
33333333333
333333333333
$ eins -s drei dreiunddreissig|calc -E -s
3.000000
33.000000
333.000000
3333.000000
33333.000000
333333.000000
3333333.000000
33333333.000000
333333333.000000
3333333333.000000
33333333333.000000
333333333333.000000
$ eins vier vierundvierzig|calc -N
4
44
444
4444
44444
444444
4444444
44444444
444444444
4444444444
44444444444
444444444444
$ eins -s vier vierundvierzig|calc -N -s
4
44
444
4444
44444
444444
4444444
44444444
444444444
4444444444
44444444444
444444444444
$ eins -s vier vierundvierzig|calc -E -s
4.000000
44.000000
444.000000
4444.000000
44444.000000
444444.000000
4444444.000000
44444444.000000
444444444.000000
4444444444.000000
44444444444.000000
444444444444.000000
$ eins fuenf fuenfundfuenfzig|calc -N
5
55
555
5555
55555
555555
5555555
55555555
555555555
5555555555
55555555555
555555555555
$ eins fuenf fuenfundfuenfzig|calc -E
5.000000
55.000000
555.000000
5555.000000
55555.000000
555555.000000
5555555.000000
55555555.000000
555555555.000000
5555555555.000000
55555555555.000000
555555555555.000000
$ eins -s fuenf fuenfundfuenfzig|calc -N -s
5
55
555
5555
55555
555555
5555555
55555555
555555555
5555555555
55555555555
555555555555
$ eins -s fuenf fuenfundfuenfzig|calc -E -s
5.000000
55.000000
555.000000
5555.000000
55555.000000
555555.000000
5555555.000000
55555555.000000
555555555.000000
5555555555.000000
55555555555.000000
555555555555.000000
$ eins sechs sechsundsechzig|calc -N
6
66
666
6666
66666
666666
6666666
66666666
666666666
6666666666
66666666666
666666666666
$ eins sechs sechsundsechzig|calc -E
6.000000
66.000000
666.000000
6666.000000
66666.000000
666666.000000
6666666.000000
66666666.000000
666666666.000000
6666666666.000000
66666666666.000000
666666666666.000000
$ eins -s sechs sechsundsechzig|calc -N -s
6
66
666
6666
66666
666666
6666666
66666666
666666666
6666666666
66666666666
666666666666
$ eins -s sechs sechsundsechzig|calc -E -s
6.000000
66.000000
666.000000
6666.000000
66666.000000
666666.000000
6666666.000000
66666666.000000
666666666.000000
6666666666.000000
66666666666.000000
666666666666.000000
$ eins sieben siebenundsiebzig|calc -N
7
77
777
7777
77777
777777
7777777
77777777
777777777
7777777777
77777777777
777777777777
$ eins sieben siebenundsiebzig|calc -E
7.000000
77.000000
777.000000
7777.000000
77777.000000
777777.000000
7777777.000000
77777777.000000
777777777.000000
7777777777.000000
77777777777.000000
777777777777.000000
$ eins -s sieben siebenundsiebzig|calc -N -s
7
77
777
7777
77777
777777
7777777
77777777
777777777
7777777777
77777777777
777777777777
$ eins -s sieben siebenundsiebzig|calc -E -s
7.000000
77.000000
777.000000
7777.000000
77777.000000
777777.000000
7777777.000000
77777777.000000
777777777.000000
7777777777.000000
77777777777.000000
777777777777.000000
$ eins acht achtundachtzig|calc -N
8
88
888
8888
88888
888888
8888888
88888888
888888888
8888888888
88888888888
888888888888
$ eins acht achtundachtzig|calc -E
8.000000
88.000000
888.000000
8888.000000
88888.000000
888888.000000
8888888.000000
88888888.000000
888888888.000000
8888888888.000000
88888888888.000000
888888888888.000000
$ eins -s acht achtundachtzig|calc -N -s
8
88
888
8888
88888
888888
8888888
88888888
888888888
8888888888
88888888888
888888888888
$ eins -s acht achtundachtzig|calc -E -s
8.000000
88.000000
888.000000
8888.000000
88888.000000
888888.000000
8888888.000000
88888888.000000
888888888.000000
8888888888.000000
88888888888.000000
888888888888.000000
$ eins neun neunundneunzig|calc -N
9
99
999
9999
99999
999999
9999999
99999999
999999999
9999999999
99999999999
999999999999
$ eins neun neunundneunzig|calc -E
9.000000
99.000000
999.000000
9999.000000
99999.000000
999999.000000
9999999.000000
99999999.000000
999999999.000000
9999999999.000000
99999999999.000000
999999999999.000000
$ eins -s neun neunundneunzig|calc -N -s
9
99
999
9999
99999
999999
9999999
99999999
999999999
9999999999
99999999999
999999999999
$ eins -s neun neunundneunzig|calc -E -s
9.000000
99.000000
999.000000
9999.000000
99999.000000
999999.000000
9999999.000000
99999999.000000
999999999.000000
9999999999.000000
99999999999.000000
999999999999.000000'
) -L eins.new <(
echo '$ test -x ./calc'
test -x ./calc 2>&1 ||
echo 'command failed: test -x ./calc'

echo '$ spaces() { ssed -R '\''s/Billi(?:arde(?:n)?|on(?:en)?)|Milli(?:arde(?:n)?|on(?:en)?)|acht|drei|e(?:in(?:e|s)?|lf)|fuenf|hundert|n(?:eun|ull)|s(?:ech(?:s)?|ieb(?:en)?|sig)|tausend|und|vier|z(?:ehn|ig|w(?:an|ei|oelf))/ \0 /g;s/ {2,}/ /g;s/^ //;s/ $//'\'' ${1:+"$1"}; }'
spaces() { ssed -R 's/Billi(?:arde(?:n)?|on(?:en)?)|Milli(?:arde(?:n)?|on(?:en)?)|acht|drei|e(?:in(?:e|s)?|lf)|fuenf|hundert|n(?:eun|ull)|s(?:ech(?:s)?|ieb(?:en)?|sig)|tausend|und|vier|z(?:ehn|ig|w(?:an|ei|oelf))/ \0 /g;s/ {2,}/ /g;s/^ //;s/ $//' ${1:+"$1"}; } 2>&1 ||
echo 'command failed: spaces() { ssed -R '\''s/Billi(?:arde(?:n)?|on(?:en)?)|Milli(?:arde(?:n)?|on(?:en)?)|acht|drei|e(?:in(?:e|s)?|lf)|fuenf|hundert|n(?:eun|ull)|s(?:ech(?:s)?|ieb(?:en)?|sig)|tausend|und|vier|z(?:ehn|ig|w(?:an|ei|oelf))/ \0 /g;s/ {2,}/ /g;s/^ //;s/ $//'\'' ${1:+"$1"}; }'

echo '$ eins() { if [ "$1" == '\''-s'\'' ]; then shift; eins "$@"|spaces; else ssed -R '\''s/elf/'\''"$2"'\''/g;s/ein[es]?/'\''"$1"'\''/g;s/(?<=Million)(?!en)/en/g'\'' ein2.txt; fi; }'
eins() { if [ "$1" == '-s' ]; then shift; eins "$@"|spaces; else ssed -R 's/elf/'"$2"'/g;s/ein[es]?/'"$1"'/g;s/(?<=Million)(?!en)/en/g' ein2.txt; fi; } 2>&1 ||
echo 'command failed: eins() { if [ "$1" == '\''-s'\'' ]; then shift; eins "$@"|spaces; else ssed -R '\''s/elf/'\''"$2"'\''/g;s/ein[es]?/'\''"$1"'\''/g;s/(?<=Million)(?!en)/en/g'\'' ein2.txt; fi; }'

echo '$ calc() { ./calc -i "$@"; }'
calc() { ./calc -i "$@"; } 2>&1 ||
echo 'command failed: calc() { ./calc -i "$@"; }'

echo '$ calc -N < ein.txt'
calc -N < ein.txt 2>&1 ||
echo 'command failed: calc -N < ein.txt'

echo '$ calc -E < ein.txt'
calc -E < ein.txt 2>&1 ||
echo 'command failed: calc -E < ein.txt'

echo '$ spaces ein.txt|calc -N -s'
spaces ein.txt|calc -N -s 2>&1 ||
echo 'command failed: spaces ein.txt|calc -N -s'

echo '$ spaces ein.txt|calc -E -s'
spaces ein.txt|calc -E -s 2>&1 ||
echo 'command failed: spaces ein.txt|calc -E -s'

echo '$ calc -N < ein2.txt'
calc -N < ein2.txt 2>&1 ||
echo 'command failed: calc -N < ein2.txt'

echo '$ calc -E < ein2.txt'
calc -E < ein2.txt 2>&1 ||
echo 'command failed: calc -E < ein2.txt'

echo '$ spaces ein2.txt|calc -N -s'
spaces ein2.txt|calc -N -s 2>&1 ||
echo 'command failed: spaces ein2.txt|calc -N -s'

echo '$ spaces ein2.txt|calc -E -s'
spaces ein2.txt|calc -E -s 2>&1 ||
echo 'command failed: spaces ein2.txt|calc -E -s'

echo '$ eins zwei zweiundzwanzig|calc -N'
eins zwei zweiundzwanzig|calc -N 2>&1 ||
echo 'command failed: eins zwei zweiundzwanzig|calc -N'

echo '$ eins zwei zweiundzwanzig|calc -E'
eins zwei zweiundzwanzig|calc -E 2>&1 ||
echo 'command failed: eins zwei zweiundzwanzig|calc -E'

echo '$ eins -s zwei zweiundzwanzig|calc -N -s'
eins -s zwei zweiundzwanzig|calc -N -s 2>&1 ||
echo 'command failed: eins -s zwei zweiundzwanzig|calc -N -s'

echo '$ eins -s zwei zweiundzwanzig|calc -E -s'
eins -s zwei zweiundzwanzig|calc -E -s 2>&1 ||
echo 'command failed: eins -s zwei zweiundzwanzig|calc -E -s'

echo '$ eins drei dreiunddreissig|calc -N'
eins drei dreiunddreissig|calc -N 2>&1 ||
echo 'command failed: eins drei dreiunddreissig|calc -N'

echo '$ eins drei dreiunddreissig|calc -E'
eins drei dreiunddreissig|calc -E 2>&1 ||
echo 'command failed: eins drei dreiunddreissig|calc -E'

echo '$ eins -s drei dreiunddreissig|calc -N -s'
eins -s drei dreiunddreissig|calc -N -s 2>&1 ||
echo 'command failed: eins -s drei dreiunddreissig|calc -N -s'

echo '$ eins -s drei dreiunddreissig|calc -E -s'
eins -s drei dreiunddreissig|calc -E -s 2>&1 ||
echo 'command failed: eins -s drei dreiunddreissig|calc -E -s'

echo '$ eins vier vierundvierzig|calc -N'
eins vier vierundvierzig|calc -N 2>&1 ||
echo 'command failed: eins vier vierundvierzig|calc -N'

echo '$ eins -s vier vierundvierzig|calc -N -s'
eins -s vier vierundvierzig|calc -N -s 2>&1 ||
echo 'command failed: eins -s vier vierundvierzig|calc -N -s'

echo '$ eins -s vier vierundvierzig|calc -E -s'
eins -s vier vierundvierzig|calc -E -s 2>&1 ||
echo 'command failed: eins -s vier vierundvierzig|calc -E -s'

echo '$ eins fuenf fuenfundfuenfzig|calc -N'
eins fuenf fuenfundfuenfzig|calc -N 2>&1 ||
echo 'command failed: eins fuenf fuenfundfuenfzig|calc -N'

echo '$ eins fuenf fuenfundfuenfzig|calc -E'
eins fuenf fuenfundfuenfzig|calc -E 2>&1 ||
echo 'command failed: eins fuenf fuenfundfuenfzig|calc -E'

echo '$ eins -s fuenf fuenfundfuenfzig|calc -N -s'
eins -s fuenf fuenfundfuenfzig|calc -N -s 2>&1 ||
echo 'command failed: eins -s fuenf fuenfundfuenfzig|calc -N -s'

echo '$ eins -s fuenf fuenfundfuenfzig|calc -E -s'
eins -s fuenf fuenfundfuenfzig|calc -E -s 2>&1 ||
echo 'command failed: eins -s fuenf fuenfundfuenfzig|calc -E -s'

echo '$ eins sechs sechsundsechzig|calc -N'
eins sechs sechsundsechzig|calc -N 2>&1 ||
echo 'command failed: eins sechs sechsundsechzig|calc -N'

echo '$ eins sechs sechsundsechzig|calc -E'
eins sechs sechsundsechzig|calc -E 2>&1 ||
echo 'command failed: eins sechs sechsundsechzig|calc -E'

echo '$ eins -s sechs sechsundsechzig|calc -N -s'
eins -s sechs sechsundsechzig|calc -N -s 2>&1 ||
echo 'command failed: eins -s sechs sechsundsechzig|calc -N -s'

echo '$ eins -s sechs sechsundsechzig|calc -E -s'
eins -s sechs sechsundsechzig|calc -E -s 2>&1 ||
echo 'command failed: eins -s sechs sechsundsechzig|calc -E -s'

echo '$ eins sieben siebenundsiebzig|calc -N'
eins sieben siebenundsiebzig|calc -N 2>&1 ||
echo 'command failed: eins sieben siebenundsiebzig|calc -N'

echo '$ eins sieben siebenundsiebzig|calc -E'
eins sieben siebenundsiebzig|calc -E 2>&1 ||
echo 'command failed: eins sieben siebenundsiebzig|calc -E'

echo '$ eins -s sieben siebenundsiebzig|calc -N -s'
eins -s sieben siebenundsiebzig|calc -N -s 2>&1 ||
echo 'command failed: eins -s sieben siebenundsiebzig|calc -N -s'

echo '$ eins -s sieben siebenundsiebzig|calc -E -s'
eins -s sieben siebenundsiebzig|calc -E -s 2>&1 ||
echo 'command failed: eins -s sieben siebenundsiebzig|calc -E -s'

echo '$ eins acht achtundachtzig|calc -N'
eins acht achtundachtzig|calc -N 2>&1 ||
echo 'command failed: eins acht achtundachtzig|calc -N'

echo '$ eins acht achtundachtzig|calc -E'
eins acht achtundachtzig|calc -E 2>&1 ||
echo 'command failed: eins acht achtundachtzig|calc -E'

echo '$ eins -s acht achtundachtzig|calc -N -s'
eins -s acht achtundachtzig|calc -N -s 2>&1 ||
echo 'command failed: eins -s acht achtundachtzig|calc -N -s'

echo '$ eins -s acht achtundachtzig|calc -E -s'
eins -s acht achtundachtzig|calc -E -s 2>&1 ||
echo 'command failed: eins -s acht achtundachtzig|calc -E -s'

echo '$ eins neun neunundneunzig|calc -N'
eins neun neunundneunzig|calc -N 2>&1 ||
echo 'command failed: eins neun neunundneunzig|calc -N'

echo '$ eins neun neunundneunzig|calc -E'
eins neun neunundneunzig|calc -E 2>&1 ||
echo 'command failed: eins neun neunundneunzig|calc -E'

echo '$ eins -s neun neunundneunzig|calc -N -s'
eins -s neun neunundneunzig|calc -N -s 2>&1 ||
echo 'command failed: eins -s neun neunundneunzig|calc -N -s'

echo '$ eins -s neun neunundneunzig|calc -E -s'
eins -s neun neunundneunzig|calc -E -s 2>&1 ||
echo 'command failed: eins -s neun neunundneunzig|calc -E -s'
)

