#!/bin/bash

# Copyright (C) 2016  Stefan Vargyas
# 
# This file is part of German-Num.
# 
# German-Num is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# German-Num is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with German-Num.  If not, see <http://www.gnu.org/licenses/>.

#
# File generated by a command like:
# $ gen-test -T empty
#

[[ "$1" =~ ^-u[0-9]+$ ]] &&
u="${1:2}" ||
u=""

diff -u$u -L empty.old <(echo \
'$ test -x ./calc
$ calc() { ./calc -Va "$@"; }
$ calc -N '\'''\''
calc: parse error:1:1: empty numeral expression
calc: parse error:1:1: 
calc: parse error:1:1: ^
command failed: calc -N '\'''\''
$ calc -E '\'''\''
calc: parse error:1:1: empty expression
calc: parse error:1:1: 
calc: parse error:1:1: ^
command failed: calc -E '\'''\''
$ calc -N '\'' '\''
calc: parse error:1:1: empty numeral expression
calc: parse error:1:1:  
calc: parse error:1:1: ^
command failed: calc -N '\'' '\''
$ calc -N '\'' '\'' -s
calc: parse error:1:1: empty numeral expression
calc: parse error:1:1:  
calc: parse error:1:1: ^
command failed: calc -N '\'' '\'' -s
$ calc -E '\'' '\''
calc: parse error:1:2: empty expression
calc: parse error:1:2:  
calc: parse error:1:2:  ^
command failed: calc -E '\'' '\''
$ calc -E '\'' '\'' -s
calc: parse error:1:2: empty expression
calc: parse error:1:2:  
calc: parse error:1:2:  ^
command failed: calc -E '\'' '\'' -s
$ calc -N z
calc: parse error:1:1: unexpected text '\''z'\''
calc: parse error:1:1: z
calc: parse error:1:1: ^
command failed: calc -N z
$ calc -E z
calc: parse error:1:1: unexpected text '\''z'\''
calc: parse error:1:1: z
calc: parse error:1:1: ^
command failed: calc -E z
$ calc -N '\'' z'\''
calc: parse error:1:2: unexpected text '\''z'\''
calc: parse error:1:2:  z
calc: parse error:1:2:  ^
command failed: calc -N '\'' z'\''
$ calc -N '\'' z'\'' -s
calc: parse error:1:2: unexpected text '\''z'\''
calc: parse error:1:2:  z
calc: parse error:1:2:  ^
command failed: calc -N '\'' z'\'' -s
$ calc -E '\'' z'\''
calc: parse error:1:2: unexpected text '\''z'\''
calc: parse error:1:2:  z
calc: parse error:1:2:  ^
command failed: calc -E '\'' z'\''
$ calc -E '\'' z'\'' -s
calc: parse error:1:2: unexpected text '\''z'\''
calc: parse error:1:2:  z
calc: parse error:1:2:  ^
command failed: calc -E '\'' z'\'' -s
$ calc -E 1z
calc: parse error:1:2: space needed after LIT token
calc: parse error:1:2: 1z
calc: parse error:1:2:  ^
command failed: calc -E 1z
$ calc -E 1z -s
calc: parse error:1:2: unexpected text '\''z'\''
calc: parse error:1:2: 1z
calc: parse error:1:2:  ^
command failed: calc -E 1z -s
$ calc -E '\''1 z'\''
calc: parse error:1:3: unexpected text '\''z'\''
calc: parse error:1:3: 1 z
calc: parse error:1:3:   ^
command failed: calc -E '\''1 z'\''
$ calc -E '\''1+z'\''
calc: parse error:1:3: unexpected text '\''z'\''
calc: parse error:1:3: 1+z
calc: parse error:1:3:   ^
command failed: calc -E '\''1+z'\''
$ calc -E 1plusz
calc: parse error:1:2: space needed after LIT token
calc: parse error:1:2: 1plusz
calc: parse error:1:2:  ^
command failed: calc -E 1plusz
$ calc -E 1plusz -s
calc: parse error:1:6: unexpected text '\''z'\''
calc: parse error:1:6: 1plusz
calc: parse error:1:6:      ^
command failed: calc -E 1plusz -s
$ calc -E '\''1 plusz'\''
calc: parse error:1:7: space needed after ADD token
calc: parse error:1:7: 1 plusz
calc: parse error:1:7:       ^
command failed: calc -E '\''1 plusz'\''
$ calc -E '\''1 plusz'\'' -s
calc: parse error:1:7: unexpected text '\''z'\''
calc: parse error:1:7: 1 plusz
calc: parse error:1:7:       ^
command failed: calc -E '\''1 plusz'\'' -s
$ calc -E '\''1 plus z'\''
calc: parse error:1:8: unexpected text '\''z'\''
calc: parse error:1:8: 1 plus z
calc: parse error:1:8:        ^
command failed: calc -E '\''1 plus z'\''
$ calc -E '\''1 plus z'\'' -s
calc: parse error:1:8: unexpected text '\''z'\''
calc: parse error:1:8: 1 plus z
calc: parse error:1:8:        ^
command failed: calc -E '\''1 plus z'\'' -s'
) -L empty.new <(
echo '$ test -x ./calc'
test -x ./calc 2>&1 ||
echo 'command failed: test -x ./calc'

echo '$ calc() { ./calc -Va "$@"; }'
calc() { ./calc -Va "$@"; } 2>&1 ||
echo 'command failed: calc() { ./calc -Va "$@"; }'

echo '$ calc -N '\'''\'''
calc -N '' 2>&1 ||
echo 'command failed: calc -N '\'''\'''

echo '$ calc -E '\'''\'''
calc -E '' 2>&1 ||
echo 'command failed: calc -E '\'''\'''

echo '$ calc -N '\'' '\'''
calc -N ' ' 2>&1 ||
echo 'command failed: calc -N '\'' '\'''

echo '$ calc -N '\'' '\'' -s'
calc -N ' ' -s 2>&1 ||
echo 'command failed: calc -N '\'' '\'' -s'

echo '$ calc -E '\'' '\'''
calc -E ' ' 2>&1 ||
echo 'command failed: calc -E '\'' '\'''

echo '$ calc -E '\'' '\'' -s'
calc -E ' ' -s 2>&1 ||
echo 'command failed: calc -E '\'' '\'' -s'

echo '$ calc -N z'
calc -N z 2>&1 ||
echo 'command failed: calc -N z'

echo '$ calc -E z'
calc -E z 2>&1 ||
echo 'command failed: calc -E z'

echo '$ calc -N '\'' z'\'''
calc -N ' z' 2>&1 ||
echo 'command failed: calc -N '\'' z'\'''

echo '$ calc -N '\'' z'\'' -s'
calc -N ' z' -s 2>&1 ||
echo 'command failed: calc -N '\'' z'\'' -s'

echo '$ calc -E '\'' z'\'''
calc -E ' z' 2>&1 ||
echo 'command failed: calc -E '\'' z'\'''

echo '$ calc -E '\'' z'\'' -s'
calc -E ' z' -s 2>&1 ||
echo 'command failed: calc -E '\'' z'\'' -s'

echo '$ calc -E 1z'
calc -E 1z 2>&1 ||
echo 'command failed: calc -E 1z'

echo '$ calc -E 1z -s'
calc -E 1z -s 2>&1 ||
echo 'command failed: calc -E 1z -s'

echo '$ calc -E '\''1 z'\'''
calc -E '1 z' 2>&1 ||
echo 'command failed: calc -E '\''1 z'\'''

echo '$ calc -E '\''1+z'\'''
calc -E '1+z' 2>&1 ||
echo 'command failed: calc -E '\''1+z'\'''

echo '$ calc -E 1plusz'
calc -E 1plusz 2>&1 ||
echo 'command failed: calc -E 1plusz'

echo '$ calc -E 1plusz -s'
calc -E 1plusz -s 2>&1 ||
echo 'command failed: calc -E 1plusz -s'

echo '$ calc -E '\''1 plusz'\'''
calc -E '1 plusz' 2>&1 ||
echo 'command failed: calc -E '\''1 plusz'\'''

echo '$ calc -E '\''1 plusz'\'' -s'
calc -E '1 plusz' -s 2>&1 ||
echo 'command failed: calc -E '\''1 plusz'\'' -s'

echo '$ calc -E '\''1 plus z'\'''
calc -E '1 plus z' 2>&1 ||
echo 'command failed: calc -E '\''1 plus z'\'''

echo '$ calc -E '\''1 plus z'\'' -s'
calc -E '1 plus z' -s 2>&1 ||
echo 'command failed: calc -E '\''1 plus z'\'' -s'
)

