#!/bin/bash

# Copyright (C) 2016  Stefan Vargyas
# 
# This file is part of German-Num.
# 
# German-Num is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# German-Num is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with German-Num.  If not, see <http://www.gnu.org/licenses/>.

#
# File generated by a command like:
# $ gen-test -T tail-char
#

[[ "$1" =~ ^-u[0-9]+$ ]] &&
u="${1:2}" ||
u=""

diff -u$u -L tail-char.old <(echo \
'$ test -x ./calc
$ calc() { ./calc -Va "$@"; }
$ calc -N '\''eine Million*zwei'\''
calc: parse error:1:13: space needed after "Million" token
calc: parse error:1:13: eine Million*zwei
calc: parse error:1:13:             ^
command failed: calc -N '\''eine Million*zwei'\''
$ calc -s -N '\''eine Million*zwei'\''
calc: parse error:1:13: unexpected text '\''*zwei'\''
calc: parse error:1:13: eine Million*zwei
calc: parse error:1:13:             ^
command failed: calc -s -N '\''eine Million*zwei'\''
$ calc -N '\''eine Million *zwei'\''
calc: parse error:1:14: unexpected text '\''*zwei'\''
calc: parse error:1:14: eine Million *zwei
calc: parse error:1:14:              ^
command failed: calc -N '\''eine Million *zwei'\''
$ calc -s -N '\''eine Million *zwei'\''
calc: parse error:1:14: unexpected text '\''*zwei'\''
calc: parse error:1:14: eine Million *zwei
calc: parse error:1:14:              ^
command failed: calc -s -N '\''eine Million *zwei'\''
$ calc -N '\''eine Million* zwei'\''
calc: parse error:1:13: space needed after "Million" token
calc: parse error:1:13: eine Million* zwei
calc: parse error:1:13:             ^
command failed: calc -N '\''eine Million* zwei'\''
$ calc -s -N '\''eine Million* zwei'\''
calc: parse error:1:13: unexpected text '\''* zwei'\''
calc: parse error:1:13: eine Million* zwei
calc: parse error:1:13:             ^
command failed: calc -s -N '\''eine Million* zwei'\''
$ calc -N '\''eine Million * zwei'\''
calc: parse error:1:14: unexpected text '\''* zwei'\''
calc: parse error:1:14: eine Million * zwei
calc: parse error:1:14:              ^
command failed: calc -N '\''eine Million * zwei'\''
$ calc -s -N '\''eine Million * zwei'\''
calc: parse error:1:14: unexpected text '\''* zwei'\''
calc: parse error:1:14: eine Million * zwei
calc: parse error:1:14:              ^
command failed: calc -s -N '\''eine Million * zwei'\''
$ calc -E '\''eine Million*zwei'\''
2000000.000000
$ calc -s -E '\''eine Million*zwei'\''
2000000.000000
$ calc -E '\''eine Million *zwei'\''
2000000.000000
$ calc -s -E '\''eine Million *zwei'\''
2000000.000000
$ calc -E '\''eine Million* zwei'\''
2000000.000000
$ calc -s -E '\''eine Million* zwei'\''
2000000.000000
$ calc -E '\''eine Million * zwei'\''
2000000.000000
$ calc -s -E '\''eine Million * zwei'\''
2000000.000000'
) -L tail-char.new <(
echo '$ test -x ./calc'
test -x ./calc 2>&1 ||
echo 'command failed: test -x ./calc'

echo '$ calc() { ./calc -Va "$@"; }'
calc() { ./calc -Va "$@"; } 2>&1 ||
echo 'command failed: calc() { ./calc -Va "$@"; }'

echo '$ calc -N '\''eine Million*zwei'\'''
calc -N 'eine Million*zwei' 2>&1 ||
echo 'command failed: calc -N '\''eine Million*zwei'\'''

echo '$ calc -s -N '\''eine Million*zwei'\'''
calc -s -N 'eine Million*zwei' 2>&1 ||
echo 'command failed: calc -s -N '\''eine Million*zwei'\'''

echo '$ calc -N '\''eine Million *zwei'\'''
calc -N 'eine Million *zwei' 2>&1 ||
echo 'command failed: calc -N '\''eine Million *zwei'\'''

echo '$ calc -s -N '\''eine Million *zwei'\'''
calc -s -N 'eine Million *zwei' 2>&1 ||
echo 'command failed: calc -s -N '\''eine Million *zwei'\'''

echo '$ calc -N '\''eine Million* zwei'\'''
calc -N 'eine Million* zwei' 2>&1 ||
echo 'command failed: calc -N '\''eine Million* zwei'\'''

echo '$ calc -s -N '\''eine Million* zwei'\'''
calc -s -N 'eine Million* zwei' 2>&1 ||
echo 'command failed: calc -s -N '\''eine Million* zwei'\'''

echo '$ calc -N '\''eine Million * zwei'\'''
calc -N 'eine Million * zwei' 2>&1 ||
echo 'command failed: calc -N '\''eine Million * zwei'\'''

echo '$ calc -s -N '\''eine Million * zwei'\'''
calc -s -N 'eine Million * zwei' 2>&1 ||
echo 'command failed: calc -s -N '\''eine Million * zwei'\'''

echo '$ calc -E '\''eine Million*zwei'\'''
calc -E 'eine Million*zwei' 2>&1 ||
echo 'command failed: calc -E '\''eine Million*zwei'\'''

echo '$ calc -s -E '\''eine Million*zwei'\'''
calc -s -E 'eine Million*zwei' 2>&1 ||
echo 'command failed: calc -s -E '\''eine Million*zwei'\'''

echo '$ calc -E '\''eine Million *zwei'\'''
calc -E 'eine Million *zwei' 2>&1 ||
echo 'command failed: calc -E '\''eine Million *zwei'\'''

echo '$ calc -s -E '\''eine Million *zwei'\'''
calc -s -E 'eine Million *zwei' 2>&1 ||
echo 'command failed: calc -s -E '\''eine Million *zwei'\'''

echo '$ calc -E '\''eine Million* zwei'\'''
calc -E 'eine Million* zwei' 2>&1 ||
echo 'command failed: calc -E '\''eine Million* zwei'\'''

echo '$ calc -s -E '\''eine Million* zwei'\'''
calc -s -E 'eine Million* zwei' 2>&1 ||
echo 'command failed: calc -s -E '\''eine Million* zwei'\'''

echo '$ calc -E '\''eine Million * zwei'\'''
calc -E 'eine Million * zwei' 2>&1 ||
echo 'command failed: calc -E '\''eine Million * zwei'\'''

echo '$ calc -s -E '\''eine Million * zwei'\'''
calc -s -E 'eine Million * zwei' 2>&1 ||
echo 'command failed: calc -s -E '\''eine Million * zwei'\'''
)

