#!/bin/bash

# Copyright (C) 2016  Stefan Vargyas
# 
# This file is part of German-Num.
# 
# German-Num is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# German-Num is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with German-Num.  If not, see <http://www.gnu.org/licenses/>.

#
# File generated by a command like:
# $ gen-test -T space3
#

[[ "$1" =~ ^-u[0-9]+$ ]] &&
u="${1:2}" ||
u=""

diff -u$u -L space3.old <(echo \
'$ test -x ./calc
$ calc() { ./calc -aVE "$@"; }
$ calc '\''einszwei'\''
calc: parse error:1:5: space needed after NUM token
calc: parse error:1:5: einszwei
calc: parse error:1:5:     ^
command failed: calc '\''einszwei'\''
$ calc '\''eins zwei'\''
calc: parse error:1:6: expected token EOE but got NUM
calc: parse error:1:6: eins zwei
calc: parse error:1:6:      ^
command failed: calc '\''eins zwei'\''
$ calc '\''einszwei'\'' -s
calc: parse error:1:5: expected token EOE but got NUM
calc: parse error:1:5: einszwei
calc: parse error:1:5:     ^
command failed: calc '\''einszwei'\'' -s
$ calc '\''eins zwei'\'' -s
calc: parse error:1:6: expected token EOE but got NUM
calc: parse error:1:6: eins zwei
calc: parse error:1:6:      ^
command failed: calc '\''eins zwei'\'' -s
$ calc '\''einszweiund'\''
calc: parse error:1:5: space needed after NUM token
calc: parse error:1:5: einszweiund
calc: parse error:1:5:     ^
command failed: calc '\''einszweiund'\''
$ calc '\''eins zweiund'\''
calc: parse error:1:13: unexpected token EON in zehn_base
calc: parse error:1:13: eins zweiund
calc: parse error:1:13:             ^
command failed: calc '\''eins zweiund'\''
$ calc '\''einszweiund'\'' -s
calc: parse error:1:12: unexpected token EON in zehn_base
calc: parse error:1:12: einszweiund
calc: parse error:1:12:            ^
command failed: calc '\''einszweiund'\'' -s
$ calc '\''eins zweiund'\'' -s
calc: parse error:1:13: unexpected token EON in zehn_base
calc: parse error:1:13: eins zweiund
calc: parse error:1:13:             ^
command failed: calc '\''eins zweiund'\'' -s'
) -L space3.new <(
echo '$ test -x ./calc'
test -x ./calc 2>&1 ||
echo 'command failed: test -x ./calc'

echo '$ calc() { ./calc -aVE "$@"; }'
calc() { ./calc -aVE "$@"; } 2>&1 ||
echo 'command failed: calc() { ./calc -aVE "$@"; }'

echo '$ calc '\''einszwei'\'''
calc 'einszwei' 2>&1 ||
echo 'command failed: calc '\''einszwei'\'''

echo '$ calc '\''eins zwei'\'''
calc 'eins zwei' 2>&1 ||
echo 'command failed: calc '\''eins zwei'\'''

echo '$ calc '\''einszwei'\'' -s'
calc 'einszwei' -s 2>&1 ||
echo 'command failed: calc '\''einszwei'\'' -s'

echo '$ calc '\''eins zwei'\'' -s'
calc 'eins zwei' -s 2>&1 ||
echo 'command failed: calc '\''eins zwei'\'' -s'

echo '$ calc '\''einszweiund'\'''
calc 'einszweiund' 2>&1 ||
echo 'command failed: calc '\''einszweiund'\'''

echo '$ calc '\''eins zweiund'\'''
calc 'eins zweiund' 2>&1 ||
echo 'command failed: calc '\''eins zweiund'\'''

echo '$ calc '\''einszweiund'\'' -s'
calc 'einszweiund' -s 2>&1 ||
echo 'command failed: calc '\''einszweiund'\'' -s'

echo '$ calc '\''eins zweiund'\'' -s'
calc 'eins zweiund' -s 2>&1 ||
echo 'command failed: calc '\''eins zweiund'\'' -s'
)

