#!/bin/bash

# Copyright (C) 2016  Stefan Vargyas
# 
# This file is part of German-Num.
# 
# German-Num is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# German-Num is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with German-Num.  If not, see <http://www.gnu.org/licenses/>.

#
# File generated by a command like:
# $ gen-test -T space
#

[[ "$1" =~ ^-u[0-9]+$ ]] &&
u="${1:2}" ||
u=""

diff -u$u -L space.old <(echo \
'$ test -x ./calc
$ calc() { ./calc -VaN "$@"; }
$ calc '\''eins'\''
1
$ calc -s '\''eins'\''
1
$ calc '\'' eins'\''
calc: parse error:1:1: space not allowed between BON and "eins" tokens
calc: parse error:1:1:  eins
calc: parse error:1:1: ^
command failed: calc '\'' eins'\''
$ calc -s '\'' eins'\''
1
$ calc '\''eins '\''
calc: parse error:1:5: space not allowed between "eins" and EON tokens
calc: parse error:1:5: eins 
calc: parse error:1:5:     ^
command failed: calc '\''eins '\''
$ calc -s '\''eins '\''
1
$ calc '\'' eins '\''
calc: parse error:1:1: space not allowed between BON and "eins" tokens
calc: parse error:1:1:  eins 
calc: parse error:1:1: ^
command failed: calc '\'' eins '\''
$ calc -s '\'' eins '\''
1
$ calc '\'' Million'\''
calc: parse error:1:2: unexpected token "Million" in numeral
calc: parse error:1:2:  Million
calc: parse error:1:2:  ^
command failed: calc '\'' Million'\''
$ calc -s '\'' Million'\''
calc: parse error:1:2: unexpected token "Million" in numeral
calc: parse error:1:2:  Million
calc: parse error:1:2:  ^
command failed: calc -s '\'' Million'\''
$ calc '\''Million'\''
calc: parse error:1:1: unexpected token "Million" in numeral
calc: parse error:1:1: Million
calc: parse error:1:1: ^
command failed: calc '\''Million'\''
$ calc -s '\''Million'\''
calc: parse error:1:1: unexpected token "Million" in numeral
calc: parse error:1:1: Million
calc: parse error:1:1: ^
command failed: calc -s '\''Million'\''
$ calc '\'' eine Million'\''
calc: parse error:1:1: space not allowed between BON and "eine" tokens
calc: parse error:1:1:  eine Million
calc: parse error:1:1: ^
command failed: calc '\'' eine Million'\''
$ calc -s '\'' eine Million'\''
1000000
$ calc '\''eine Million'\''
1000000
$ calc -s '\''eine Million'\''
1000000
$ calc '\''eineMillion'\''
calc: parse error:1:5: space needed between "eine" and "Million" tokens
calc: parse error:1:5: eineMillion
calc: parse error:1:5:     ^
command failed: calc '\''eineMillion'\''
$ calc -s '\''eineMillion'\''
1000000
$ calc '\''eine Million eins'\''
1000001
$ calc -s '\''eine Million eins'\''
1000001
$ calc '\''eine Millioneins'\''
calc: parse error:1:13: space needed after "Million" token
calc: parse error:1:13: eine Millioneins
calc: parse error:1:13:             ^
command failed: calc '\''eine Millioneins'\''
$ calc -s '\''eine Millioneins'\''
1000001
$ calc '\''einundvierzig'\''
41
$ calc -s '\''einundvierzig'\''
41
$ calc '\''einund vierzig'\''
calc: parse error:1:7: space not allowed between "und" and "vier" tokens
calc: parse error:1:7: einund vierzig
calc: parse error:1:7:       ^
command failed: calc '\''einund vierzig'\''
$ calc -s '\''einund vierzig'\''
41'
) -L space.new <(
echo '$ test -x ./calc'
test -x ./calc 2>&1 ||
echo 'command failed: test -x ./calc'

echo '$ calc() { ./calc -VaN "$@"; }'
calc() { ./calc -VaN "$@"; } 2>&1 ||
echo 'command failed: calc() { ./calc -VaN "$@"; }'

echo '$ calc '\''eins'\'''
calc 'eins' 2>&1 ||
echo 'command failed: calc '\''eins'\'''

echo '$ calc -s '\''eins'\'''
calc -s 'eins' 2>&1 ||
echo 'command failed: calc -s '\''eins'\'''

echo '$ calc '\'' eins'\'''
calc ' eins' 2>&1 ||
echo 'command failed: calc '\'' eins'\'''

echo '$ calc -s '\'' eins'\'''
calc -s ' eins' 2>&1 ||
echo 'command failed: calc -s '\'' eins'\'''

echo '$ calc '\''eins '\'''
calc 'eins ' 2>&1 ||
echo 'command failed: calc '\''eins '\'''

echo '$ calc -s '\''eins '\'''
calc -s 'eins ' 2>&1 ||
echo 'command failed: calc -s '\''eins '\'''

echo '$ calc '\'' eins '\'''
calc ' eins ' 2>&1 ||
echo 'command failed: calc '\'' eins '\'''

echo '$ calc -s '\'' eins '\'''
calc -s ' eins ' 2>&1 ||
echo 'command failed: calc -s '\'' eins '\'''

echo '$ calc '\'' Million'\'''
calc ' Million' 2>&1 ||
echo 'command failed: calc '\'' Million'\'''

echo '$ calc -s '\'' Million'\'''
calc -s ' Million' 2>&1 ||
echo 'command failed: calc -s '\'' Million'\'''

echo '$ calc '\''Million'\'''
calc 'Million' 2>&1 ||
echo 'command failed: calc '\''Million'\'''

echo '$ calc -s '\''Million'\'''
calc -s 'Million' 2>&1 ||
echo 'command failed: calc -s '\''Million'\'''

echo '$ calc '\'' eine Million'\'''
calc ' eine Million' 2>&1 ||
echo 'command failed: calc '\'' eine Million'\'''

echo '$ calc -s '\'' eine Million'\'''
calc -s ' eine Million' 2>&1 ||
echo 'command failed: calc -s '\'' eine Million'\'''

echo '$ calc '\''eine Million'\'''
calc 'eine Million' 2>&1 ||
echo 'command failed: calc '\''eine Million'\'''

echo '$ calc -s '\''eine Million'\'''
calc -s 'eine Million' 2>&1 ||
echo 'command failed: calc -s '\''eine Million'\'''

echo '$ calc '\''eineMillion'\'''
calc 'eineMillion' 2>&1 ||
echo 'command failed: calc '\''eineMillion'\'''

echo '$ calc -s '\''eineMillion'\'''
calc -s 'eineMillion' 2>&1 ||
echo 'command failed: calc -s '\''eineMillion'\'''

echo '$ calc '\''eine Million eins'\'''
calc 'eine Million eins' 2>&1 ||
echo 'command failed: calc '\''eine Million eins'\'''

echo '$ calc -s '\''eine Million eins'\'''
calc -s 'eine Million eins' 2>&1 ||
echo 'command failed: calc -s '\''eine Million eins'\'''

echo '$ calc '\''eine Millioneins'\'''
calc 'eine Millioneins' 2>&1 ||
echo 'command failed: calc '\''eine Millioneins'\'''

echo '$ calc -s '\''eine Millioneins'\'''
calc -s 'eine Millioneins' 2>&1 ||
echo 'command failed: calc -s '\''eine Millioneins'\'''

echo '$ calc '\''einundvierzig'\'''
calc 'einundvierzig' 2>&1 ||
echo 'command failed: calc '\''einundvierzig'\'''

echo '$ calc -s '\''einundvierzig'\'''
calc -s 'einundvierzig' 2>&1 ||
echo 'command failed: calc -s '\''einundvierzig'\'''

echo '$ calc '\''einund vierzig'\'''
calc 'einund vierzig' 2>&1 ||
echo 'command failed: calc '\''einund vierzig'\'''

echo '$ calc -s '\''einund vierzig'\'''
calc -s 'einund vierzig' 2>&1 ||
echo 'command failed: calc -s '\''einund vierzig'\'''
)

