#!/bin/bash

# Copyright (C) 2016  Stefan Vargyas
# 
# This file is part of German-Num.
# 
# German-Num is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# German-Num is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with German-Num.  If not, see <http://www.gnu.org/licenses/>.

#
# File generated by a command like:
# $ gen-test -T space2
#

[[ "$1" =~ ^-u[0-9]+$ ]] &&
u="${1:2}" ||
u=""

diff -u$u -L space2.old <(echo \
'$ test -x ./calc
$ calc() { ./calc -aVE "$@"; }
$ calc '\''eineMillionpluszweiMillionen'\''
calc: parse error:1:5: space needed between "eine" and "Million" tokens
calc: parse error:1:5: eineMillionpluszweiMillionen
calc: parse error:1:5:     ^
command failed: calc '\''eineMillionpluszweiMillionen'\''
$ calc '\''eine MillionpluszweiMillionen'\''
calc: parse error:1:13: space needed after "Million" token
calc: parse error:1:13: eine MillionpluszweiMillionen
calc: parse error:1:13:             ^
command failed: calc '\''eine MillionpluszweiMillionen'\''
$ calc '\''eine Million pluszweiMillionen'\''
calc: parse error:1:18: space needed after ADD token
calc: parse error:1:18: eine Million pluszweiMillionen
calc: parse error:1:18:                  ^
command failed: calc '\''eine Million pluszweiMillionen'\''
$ calc '\''eine Million plus zweiMillionen'\''
calc: parse error:1:23: space needed between "zwei" and "Millionen" tokens
calc: parse error:1:23: eine Million plus zweiMillionen
calc: parse error:1:23:                       ^
command failed: calc '\''eine Million plus zweiMillionen'\''
$ calc '\''eine Million plus zwei Millionen'\''
3000000.000000'
) -L space2.new <(
echo '$ test -x ./calc'
test -x ./calc 2>&1 ||
echo 'command failed: test -x ./calc'

echo '$ calc() { ./calc -aVE "$@"; }'
calc() { ./calc -aVE "$@"; } 2>&1 ||
echo 'command failed: calc() { ./calc -aVE "$@"; }'

echo '$ calc '\''eineMillionpluszweiMillionen'\'''
calc 'eineMillionpluszweiMillionen' 2>&1 ||
echo 'command failed: calc '\''eineMillionpluszweiMillionen'\'''

echo '$ calc '\''eine MillionpluszweiMillionen'\'''
calc 'eine MillionpluszweiMillionen' 2>&1 ||
echo 'command failed: calc '\''eine MillionpluszweiMillionen'\'''

echo '$ calc '\''eine Million pluszweiMillionen'\'''
calc 'eine Million pluszweiMillionen' 2>&1 ||
echo 'command failed: calc '\''eine Million pluszweiMillionen'\'''

echo '$ calc '\''eine Million plus zweiMillionen'\'''
calc 'eine Million plus zweiMillionen' 2>&1 ||
echo 'command failed: calc '\''eine Million plus zweiMillionen'\'''

echo '$ calc '\''eine Million plus zwei Millionen'\'''
calc 'eine Million plus zwei Millionen' 2>&1 ||
echo 'command failed: calc '\''eine Million plus zwei Millionen'\'''
)

