#!/bin/bash

# Copyright (C) 2016  Stefan Vargyas
# 
# This file is part of German-Num.
# 
# German-Num is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# German-Num is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with German-Num.  If not, see <http://www.gnu.org/licenses/>.

#
# File generated by a command like:
# $ gen-test -T calc
#

[[ "$1" =~ ^-u[0-9]+$ ]] &&
u="${1:2}" ||
u=""

diff -u$u -L calc.old <(echo \
'$ test -x ./calc
$ calc() { ./calc -aE "$@"; }
$ calc '\''dreihundertzweiundneunzig mal 7'\'' '\''12 minus 3'\''
2744.000000
9.000000'
) -L calc.new <(
echo '$ test -x ./calc'
test -x ./calc 2>&1 ||
echo 'command failed: test -x ./calc'

echo '$ calc() { ./calc -aE "$@"; }'
calc() { ./calc -aE "$@"; } 2>&1 ||
echo 'command failed: calc() { ./calc -aE "$@"; }'

echo '$ calc '\''dreihundertzweiundneunzig mal 7'\'' '\''12 minus 3'\'''
calc 'dreihundertzweiundneunzig mal 7' '12 minus 3' 2>&1 ||
echo 'command failed: calc '\''dreihundertzweiundneunzig mal 7'\'' '\''12 minus 3'\'''
)

