#!/bin/bash

# Copyright (C) 2016  Stefan Vargyas
# 
# This file is part of German-Num.
# 
# German-Num is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# German-Num is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with German-Num.  If not, see <http://www.gnu.org/licenses/>.

#
# File generated by a command like:
# $ gen-test -T neun
#

[[ "$1" =~ ^-u[0-9]+$ ]] &&
u="${1:2}" ||
u=""

diff -u$u -L neun.old <(echo \
'$ test -x ./calc
$ calc() { ./calc -aN "$@"; }
$ calc '\''neunhundertneunundneunzigtausendneunhundertneunundneunzig Millionen'\''
999999000000
$ calc -s '\''neun hundert neun und neun zig tausend neun hundert neun und neun zig Millionen'\''
999999000000
$ calc '\''neunhundertneunundneunzigtausendneunhundertneunundneunzig Millionen neunhundertneunundneunzigtausendneunhundertneunundneunzig'\''
999999999999
$ calc -s '\''neun hundert neun und neun zig tausend neun hundert neun und neun zig Millionen neun hundert neun und neun zig tausend neun hundert neun und neun zig'\''
999999999999'
) -L neun.new <(
echo '$ test -x ./calc'
test -x ./calc 2>&1 ||
echo 'command failed: test -x ./calc'

echo '$ calc() { ./calc -aN "$@"; }'
calc() { ./calc -aN "$@"; } 2>&1 ||
echo 'command failed: calc() { ./calc -aN "$@"; }'

echo '$ calc '\''neunhundertneunundneunzigtausendneunhundertneunundneunzig Millionen'\'''
calc 'neunhundertneunundneunzigtausendneunhundertneunundneunzig Millionen' 2>&1 ||
echo 'command failed: calc '\''neunhundertneunundneunzigtausendneunhundertneunundneunzig Millionen'\'''

echo '$ calc -s '\''neun hundert neun und neun zig tausend neun hundert neun und neun zig Millionen'\'''
calc -s 'neun hundert neun und neun zig tausend neun hundert neun und neun zig Millionen' 2>&1 ||
echo 'command failed: calc -s '\''neun hundert neun und neun zig tausend neun hundert neun und neun zig Millionen'\'''

echo '$ calc '\''neunhundertneunundneunzigtausendneunhundertneunundneunzig Millionen neunhundertneunundneunzigtausendneunhundertneunundneunzig'\'''
calc 'neunhundertneunundneunzigtausendneunhundertneunundneunzig Millionen neunhundertneunundneunzigtausendneunhundertneunundneunzig' 2>&1 ||
echo 'command failed: calc '\''neunhundertneunundneunzigtausendneunhundertneunundneunzig Millionen neunhundertneunundneunzigtausendneunhundertneunundneunzig'\'''

echo '$ calc -s '\''neun hundert neun und neun zig tausend neun hundert neun und neun zig Millionen neun hundert neun und neun zig tausend neun hundert neun und neun zig'\'''
calc -s 'neun hundert neun und neun zig tausend neun hundert neun und neun zig Millionen neun hundert neun und neun zig tausend neun hundert neun und neun zig' 2>&1 ||
echo 'command failed: calc -s '\''neun hundert neun und neun zig tausend neun hundert neun und neun zig Millionen neun hundert neun und neun zig tausend neun hundert neun und neun zig'\'''
)

